site_name: ml-vision-lab
repo_url: https://github.com/bkm82/ml-vision-lab
site_url: https://bkm82.github.io/ml-vision-lab
site_description: This is a personal sandbox project to test machine learning and computer vision projects
site_author: Bray Moll
edit_uri: edit/main/docs/
repo_name: bkm82/ml-vision-lab
copyright: Maintained by <a href="https://bkm82.com">bkm82</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/ml_vision_lab"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bkm82/ml-vision-lab
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ml-vision-lab

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
